### ISSUE TITLE
Use `regex.escape()`

### ISSUE THREAD

**Issue by peldszus** [MaxHalford/orc#2]
In the [blog post](https://maxhalford.github.io/blog/fuzzy-regex-matching-in-python/) as well as in the notebook `approximate-matching.ipynb` checked in this repo, you do replacement on the specimen string that becomes a part of the regex.

```python
pattern = specimen.replace('-', r'\-')
```

My assumption is that this is for handling characters, that have special meaning in regexes.

If that is true, I'd propose to use `regex.escape()` which does exactly that for all relevent symbols.

**Comment by MaxHalford** [comment]
Ah! Beautiful. Thanks a lot, just updated the notebook 👍
